DROP DATABASE IF EXISTS VideoGames;
CREATE DATABASE VideoGames;
USE VideoGames;

CREATE TABLE IF NOT EXISTS Games(
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(50) NOT NULL,
publisher VARCHAR(50) NOT NULL,
genre VARCHAR(50) NOT NULL,
multiplayer BOOLEAN,
rating VARCHAR(4) NOT NULL,
PRIMARY KEY(id)
);